<!DOCTYPE html>
<html>
<head>
    <link rel="stylesheet" type="text/css" href="travel.css">

     <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="animate.css">
    <!--Fontawesome CDN-->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="landingpage.css">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>
      <link rel="stylesheet" type="text/css" href="travel.css">
<link href = "https://code.jquery.com/ui/1.10.4/themes/ui-lightness/jquery-ui.css"
         rel = "stylesheet">
      <script src = "https://code.jquery.com/jquery-1.10.2.js"></script>
      <script src = "https://code.jquery.com/ui/1.10.4/jquery-ui.js"></script>
    

    <?php

if(isset($_GET['t']))
{

search();
}
function search()
{
  
 $my_file = 'file.txt';
$handle = fopen($my_file, 'w') or die('Cannot open file:  '.$my_file);
$data = $_POST['searchValue'];

fwrite($handle, $data);
fclose($handle);
$servername = "localhost";
$username = "root";
$password = "";
$db_name="iwp_project";
$conn = new mysqli($servername, $username, $password,$db_name);
if (($conn->connect_error)) {
    die("Connection failed: " . $conn->connect_error);
} 

$ssql="insert into mostsearched values('".$data."')";
$conn->query($ssql);

//$resultarray=json_decode($result);
newsearch();

$url='Location: listings.php?search='.$data;
header($url);

 

}
function newsearch()
{
    
  exec("hi.py");
  
}

    ?>

      <script>
         $(function() {
            var availableTutorials = [ "Mumbai"
,"Delhi"
,"Bengaluru"
,"Ahmedabad"
,"Hyderabad"
,"Chennai"
,"Kolkata"
,"Pune"
,"Jaipur"
,"Surat"
,"Lucknow"
,"Kanpur"
,"Nagpur"
,"Patna"
,"Indore"
,"Thane"
,"Bhopal"
,"Visakhapatnam"
,"Vadodara"
,"Firozabad"
,"Ludhiana"
,"Rajkot"
,"Agra"
,"Siliguri"
,"Nashik"
,"Faridabad"
,"Patiala"
,"Meerut"
,"Kalyan-Dombivali"
,"Vasai-Virar"
,"Varanasi"
,"Srinagar"
,"Dhanbad"
,"Jodhpur"
,"Amritsar"
,"Raipur"
,"Allahabad"
,"Coimbatore"
,"Jabalpur"
,"Gwalior"
,"Vijayawada"
,"Madurai"
,"Guwahati"
,"Chandigarh"
,"Hubli-Dharwad"
,"Amroha"
,"Moradabad"
,"Gurgaon"
,"Aligarh"
,"Solapur"
,"Ranchi"
,"Jalandhar"
,"Tiruchirappalli"
,"Bhubaneswar"
,"Salem"
,"Warangal"
,"Mira-Bhayandar"
,"Thiruvananthapuram"
,"Bhiwandi"
,"Saharanpur"
,"Guntur"
,"Amravati"
,"Bikaner"
,"Noida"
,"Jamshedpur"
,"Bhilai Nagar"
,"Cuttack"
,"Kochi"
,"Udaipur"
,"Bhavnagar"
,"Dehradun"
,"Asansol"
,"Nanded-Waghala"
,"Ajmer"
,"Jamnagar"
,"Ujjain"
,"Sangli"
,"Loni"
,"Jhansi"
,"Pondicherry"
,"Nellore"
,"Jammu"
,"Belagavi"
,"Raurkela"
,"Mangaluru"
,"Tirunelveli"
,"Malegaon"
,"Gaya"
,"Tiruppur"
,"Davanagere"
,"Kozhikode"
,"Akola"
,"Kurnool"
,"Bokaro Steel City"
,"Rajahmundry"
,"Ballari"
,"Agartala"
,"Bhagalpur"
,"Latur"
,"Dhule"
,"Korba"
,"Bhilwara"
,"Brahmapur"
,"Mysore"
,"Muzaffarpur"
,"Ahmednagar"
,"Kollam"
,"Raghunathganj"
,"Bilaspur"
,"Shahjahanpur"
,"Thrissur"
,"Alwar"
,"Kakinada"
,"Nizamabad"
,"Sagar"
,"Tumkur"
,"Hisar"
,"Rohtak"
,"Panipat"
,"Darbhanga"
,"Kharagpur"
,"Aizawl"
,"Ichalkaranji"
,"Tirupati"
,"Karnal"
,"Bathinda"
,"Rampur"
,"Shivamogga"
,"Ratlam"
,"Modinagar"
,"Durg"
,"Shillong"
,"Imphal"
,"Hapur"
,"Ranipet"
,"Anantapur"
,"Arrah"
,"Karimnagar"
,"Parbhani"
,"Etawah"
,"Bharatpur"
,"Begusarai"
,"New Delhi"
,"Chhapra"
,"Kadapa"
,"Ramagundam"
,"Pali"
,"Satna"
,"Vizianagaram"
,"Katihar"
,"Hardwar"
,"Sonipat"
,"Nagercoil"
,"Thanjavur"
,"Murwara (Katni)"
,"Naihati"
,"Sambhal"
,"Nadiad"
,"Yamunanagar"
,"English Bazar"
,"Eluru"
,"Munger"
,"Panchkula"
,"Raayachuru"
,"Panvel"
,"Deoghar"
,"Ongole"
,"Nandyal"
,"Morena"
,"Bhiwani"
,"Porbandar"
,"Palakkad"
,"Anand"
,"Purnia"
,"Baharampur"
,"Barmer"
,"Morvi"
,"Orai"
,"Bahraich"
,"Sikar"
,"Vellore"
,"Singrauli"
,"Khammam"
,"Mahesana"
,"Silchar"
,"Sambalpur"
,"Rewa"
,"Unnao"
,"Hugli-Chinsurah"
,"Raiganj"
,"Phusro"
,"Adityapur"
,"Alappuzha"
,"Bahadurgarh"
,"Machilipatnam"
,"Rae Bareli"
,"Jalpaiguri"
,"Bharuch"
,"Pathankot"
,"Hoshiarpur"
,"Baramula"
,"Adoni"
,"Jind"
,"Tonk"
,"Tenali"
,"Kancheepuram"
,"Vapi"
,"Sirsa"
,"Navsari"
,"Mahbubnagar"
,"Puri"
,"Robertson Pet"
,"Erode"
,"Batala"
,"Haldwani-cum-Kathgodam"
,"Vidisha"
,"Saharsa"
,"Thanesar"
,"Chittoor"
,"Veraval"
,"Lakhimpur"
,"Sitapur"
,"Hindupur"
,"Santipur"
,"Balurghat"
,"Ganjbasoda"
,"Moga"
,"Proddatur"
,"Srinagar"
,"Medinipur"
,"Habra"
,"Sasaram"
,"Hajipur"
,"Bhuj"
,"Shivpuri"
,"Ranaghat"
,"Shimla"
,"Tiruvannamalai"
,"Kaithal"
,"Rajnandgaon"
,"Godhra"
,"Hazaribag"
,"Bhimavaram"
,"Mandsaur"
,"Dibrugarh"
,"Kolar"
,"Bankura"
,"Mandya"
,"Dehri-on-Sone"
,"Madanapalle"
,"Malerkotla"
,"Lalitpur"
,"Bettiah"
,"Pollachi"
,"Khanna"
,"Neemuch"
,"Palwal"
,"Palanpur"
,"Guntakal"
,"Nabadwip"
,"Udupi"
,"Jagdalpur"
,"Motihari"
,"Pilibhit"
,"Dimapur"
,"Mohali"
,"Sadulpur"
,"Rajapalayam"
,"Dharmavaram"
,"Kashipur"
,"Sivakasi"
,"Darjiling"
,"Chikkamagaluru"
,"Gudivada"
,"Baleshwar Town"
,"Mancherial"
,"Srikakulam"
,"Adilabad"
,"Yavatmal"
,"Barnala"
,"Nagaon"
,"Narasaraopet"
,"Raigarh"
,"Roorkee"
,"Valsad"
,"Ambikapur"
,"Giridih"
,"Chandausi"
,"Purulia"
,"Patan"
,"Bagaha"
,"Hardoi "
,"Achalpur"
,"Osmanabad"
,"Deesa"
,"Nandurbar"
,"Azamgarh"
,"Ramgarh"
,"Firozpur"
,"Baripada Town"
,"Karwar"
,"Siwan"
,"Rajampet"
,"Pudukkottai"
,"Anantnag"
,"Tadpatri"
,"Satara"
,"Bhadrak"
,"Kishanganj"
,"Suryapet"
,"Wardha"
,"Ranebennuru"
,"Amreli"
,"Neyveli (TS)"
,"Jamalpur"
,"Marmagao"
,"Udgir"
,"Tadepalligudem"
,"Nagapattinam"
,"Buxar"
,"Aurangabad"
,"Jehanabad"
,"Phagwara"
,"Khair"
,"Sawai Madhopur"
,"Kapurthala"
,"Chilakaluripet"
,"Aurangabad"
,"Malappuram"
,"Rewari"
,"Nagaur"
,"Sultanpur"
,"Nagda"
,"Port Blair"
,"Lakhisarai"
,"Panaji"
,"Tinsukia"
,"Itarsi"
,"Kohima"
,"Balangir"
,"Nawada"
,"Jharsuguda"
,"Jagtial"
,"Viluppuram"
,"Amalner"
,"Zirakpur"
,"Tanda"
,"Tiruchengode"
,"Nagina"
,"Yemmiganur"
,"Vaniyambadi"
,"Sarni"
,"Theni Allinagaram"
,"Margao"
,"Akot"
,"Sehore"
,"Mhow Cantonment"
,"Kot Kapura"
,"Makrana"
,"Pandharpur"
,"Miryalaguda"
,"Shamli"
,"Seoni"
,"Ranibennur"
,"Kadiri"
,"Shrirampur"
,"Rudrapur"
,"Parli"
,"Najibabad"
,"Nirmal"
,"Udhagamandalam"
,"Shikohabad"
,"Jhumri Tilaiya"
,"Aruppukkottai"
,"Ponnani"
,"Jamui"
,"Sitamarhi"
,"Chirala"
,"Anjar"
,"Karaikal"
,"Hansi"
,"Anakapalle"
,"Mahasamund"
,"Faridkot"
,"Saunda"
,"Dhoraji"
,"Paramakudi"
,"Balaghat"
,"Sujangarh"
,"Khambhat"
,"Muktsar"
,"Rajpura"
,"Kavali"
,"Dhamtari"
,"Ashok Nagar"
,"Sardarshahar"
,"Mahuva"
,"Bargarh"
,"Kamareddy"
,"Sahibganj"
,"Kothagudem"
,"Ramanagaram"
,"Gokak"
,"Tikamgarh"
,"Araria"
,"Rishikesh"
,"Shahdol"
,"Medininagar (Daltonganj)"
,"Arakkonam"
,"Washim"
,"Sangrur"
,"Bodhan"
,"Fazilka"
,"Palacole"
,"Keshod"
,"Sullurpeta"
,"Wadhwan"
,"Gurdaspur"
,"Vatakara"
,"Tura"
,"Narnaul"
,"Kharar"
,"Yadgir"
,"Ambejogai"
,"Ankleshwar"
,"Savarkundla"
,"Paradip"
,"Virudhachalam"
,"Kanhangad"
,"Kadi"
,"Srivilliputhur"
,"Gobindgarh"
,"Tindivanam"
,"Mansa"
,"Taliparamba"
,"Manmad"
,"Tanuku"
,"Rayachoti"
,"Virudhunagar"
,"Koyilandy"
,"Jorhat"
,"Karur"
,"Valparai"
,"Srikalahasti"
,"Neyyattinkara"
,"Bapatla"
,"Fatehabad"
,"Malout"
,"Sankarankovil"
,"Tenkasi"
,"Ratnagiri"
,"Rabkavi Banhatti"
,"Sikandrabad"
,"Chaibasa"
,"Chirmiri"
,"Palwancha"
,"Bhawanipatna"
,"Kayamkulam"
,"Pithampur"
,"Nabha"
,"Shahabad, Hardoi"
,"Dhenkanal"
,"Uran Islampur"
,"Gopalganj"
,"Bongaigaon City"
,"Palani"
,"Pusad"
,"Sopore"
,"Pilkhuwa"
,"Tarn Taran"
,"Renukoot"
,"Mandamarri"
,"Shahabad"
,"Barbil"
,"Koratla"
,"Madhubani"
,"Arambagh"
,"Gohana"
,"Ladnu"
,"Pattukkottai"
,"Sirsi"
,"Sircilla"
,"Tamluk"
,"Jagraon"
,"AlipurdUrban Agglomerationr"
,"Alirajpur"
,"Tandur"
,"Naidupet"
,"Tirupathur"
,"Tohana"
,"Ratangarh"
,"Dhubri"
,"Masaurhi"
,"Visnagar"
,"Vrindavan"
,"Nokha"
,"Nagari"
,"Narwana"
,"Ramanathapuram"
,"Ujhani"
,"Samastipur"
,"Laharpur"
,"Sangamner"
,"Nimbahera"
,"Siddipet"
,"Suri"
,"Diphu"
,"Jhargram"
,"Shirpur-Warwade"
,"Tilhar"
,"Sindhnur"
,"Udumalaipettai"
,"Malkapur"
,"Wanaparthy"
,"Gudur"
,"Kendujhar"
,"Mandla"
,"Mandi"
,"Nedumangad"
,"North Lakhimpur"
,"Vinukonda"
,"Tiptur"
,"Gobichettipalayam"
,"Sunabeda"
,"Wani"
,"Upleta"
,"Narasapuram"
,"Nuzvid"
,"Tezpur"
,"Una"
,"Markapur"
,"Sheopur"
,"Thiruvarur"
,"Sidhpur"
,"Sahaswan"
,"Suratgarh"
,"Shajapur"
,"Rayagada"
,"Lonavla"
,"Ponnur"
,"Kagaznagar"
,"Gadwal"
,"Bhatapara"
,"Kandukur"
,"Sangareddy"
,"Unjha"
,"Lunglei"
,"Karimganj"
,"Kannur"
,"Bobbili"
,"Mokameh"
,"Talegaon Dabhade"
,"Anjangaon"
,"Mangrol"
,"Sunam"
,"Gangarampur"
,"Thiruvallur"
,"Tirur"
,"Rath"
,"Jatani"
,"Viramgam"
,"Rajsamand"
,"Yanam"
,"Kottayam"
,"Panruti"
,"Dhuri"
,"Namakkal"
,"Kasaragod"
,"Modasa"
,"Rayadurg"
,"Supaul"
,"Kunnamkulam"
,"Umred"
,"Bellampalle"
,"Sibsagar"
,"Mandi Dabwali"
,"Ottappalam"
,"Dumraon"
,"Samalkot"
,"Jaggaiahpet"
,"Goalpara"
,"Tuni"
,"Lachhmangarh"
,"Bhongir"
,"Amalapuram"
,"Firozpur Cantt."
,"Vikarabad"
,"Thiruvalla"
,"Sherkot"
,"Palghar"
,"Shegaon"
,"Jangaon"
,"Bheemunipatnam"
,"Panna"
,"Thodupuzha"
,"KathUrban Agglomeration"
,"Palitana"
,"Arwal"
,"Venkatagiri"
,"Kalpi"
,"Rajgarh (Churu)"
,"Sattenapalle"
,"Arsikere"
,"Ozar"
,"Thirumangalam"
,"Petlad"
,"Nasirabad"
,"Phaltan"
,"Rampurhat"
,"Nanjangud"
,"Forbesganj"
,"Tundla"
,"BhabUrban Agglomeration"
,"Sagara"
,"Pithapuram"
,"Sira"
,"Bhadrachalam"
,"Charkhi Dadri"
,"Chatra"
,"Palasa Kasibugga"
,"Nohar"
,"Yevla"
,"Sirhind Fatehgarh Sahib"
,"Bhainsa"
,"Parvathipuram"
,"Shahade"
,"Chalakudy"
,"Narkatiaganj"
,"Kapadvanj"
,"Macherla"
,"Raghogarh-Vijaypur"
,"Rupnagar"
,"Naugachhia"
,"Sendhwa"
,"Byasanagar"
,"Sandila"
,"Gooty"
,"Salur"
,"Nanpara"
,"Sardhana"
,"Vita"
,"Gumia"
,"Puttur"
,"Jalandhar Cantt."
,"Nehtaur"
,"Changanassery"
,"Mandapeta"
,"Dumka"
,"Seohara"
,"Umarkhed"
,"Madhupur"
,"Vikramasingapuram"
,"Punalur"
,"Kendrapara"
,"Sihor"
,"Nellikuppam"
,"Samana"
,"Warora"
,"Nilambur"
,"Rasipuram"
,"Ramnagar"
,"Jammalamadugu"
,"Nawanshahr"
,"Thoubal"
,"Athni"
,"Cherthala"
,"Sidhi"
,"Farooqnagar"
,"Peddapuram"
,"Chirkunda"
,"Pachora"
,"Madhepura"
,"Pithoragarh"
,"Tumsar"
,"Phalodi"
,"Tiruttani"
,"Rampura Phul"
,"Perinthalmanna"
,"Padrauna"
,"Pipariya"
,"Dalli-Rajhara"
,"Punganur"
,"Mattannur"
,"Mathura"
,"Thakurdwara"
,"Nandivaram-Guduvancheri"
,"Mulbagal"
,"Manjlegaon"
,"Wankaner"
,"Sillod"
,"Nidadavole"
,"Surapura"
,"Rajagangapur"
,"Sheikhpura"
,"Parlakhemundi"
,"Kalimpong"
,"Siruguppa"
,"Arvi"
,"Limbdi"
,"Barpeta"
,"Manglaur"
,"Repalle"
,"Mudhol"
,"Shujalpur"
,"Mandvi"
,"Thangadh"
,"Sironj"
,"Nandura"
,"Shoranur"
,"Nathdwara"
,"Periyakulam"
,"Sultanganj"
,"Medak"
,"Narayanpet"
,"Raxaul Bazar"
,"Rajauri"
,"Pernampattu"
,"Nainital"
,"Ramachandrapuram"
,"Vaijapur"
,"Nangal"
,"Sidlaghatta"
,"Punch"
,"Pandhurna"
,"Wadgaon Road"
,"Talcher"
,"Varkala"
,"Pilani"
,"Nowgong"
,"Naila Janjgir"
,"Mapusa"
,"Vellakoil"
,"Merta City"
,"Sivaganga"
,"Mandideep"
,"Sailu"
,"Vyara"
,"Kovvur"
,"Vadalur"
,"Nawabganj"
,"Padra"
,"Sainthia"
,"Siana"
,"Shahpur"
,"Sojat"
,"Noorpur"
,"Paravoor"
,"Murtijapur"
,"Ramnagar"
,"Sundargarh"
,"Taki"
,"Saundatti-Yellamma"
,"Pathanamthitta"
,"Wadi"
,"Rameshwaram"
,"Tasgaon"
,"Sikandra Rao"
,"Sihora"
,"Tiruvethipuram"
,"Tiruvuru"
,"Mehkar"
,"Peringathur"
,"Perambalur"
,"Manvi"
,"Zunheboto"
,"Mahnar Bazar"
,"Attingal"
,"Shahbad"
,"Puranpur"
,"Nelamangala"
,"Nakodar"
,"Lunawada"
,"Murshidabad"
,"Mahe"
,"Lanka"
,"Rudauli"
,"Tuensang"
,"Lakshmeshwar"
,"Zira"
,"Yawal"
,"Thana Bhawan"
,"Ramdurg"
,"Pulgaon"
,"Sadasivpet"
,"Nargund"
,"Neem-Ka-Thana"
,"Memari"
,"Nilanga"
,"Naharlagun"
,"Pakaur"
,"Wai"
,"Tarikere"
,"Malavalli"
,"Raisen"
,"Lahar"
,"Uravakonda"
,"Savanur"
,"Sirohi"
,"Udhampur"
,"Umarga"
,"Pratapgarh"
,"Lingsugur"
,"Usilampatti"
,"Palia Kalan"
,"Wokha"
,"Rajpipla"
,"Vijayapura"
,"Rawatbhata"
,"Sangaria"
,"Paithan"
,"Rahuri"
,"Patti"
,"Zaidpur"
,"Lalsot"
,"Maihar"
,"Vedaranyam"
,"Nawapur"
,"Solan"
,"Vapi"
,"Sanawad"
,"Warisaliganj"
,"Revelganj"
,"Sabalgarh"
,"Tuljapur"
,"Simdega"
,"Musabani"
,"Kodungallur"
,"Phulabani"
,"Umreth"
,"Narsipatnam"
,"Nautanwa"
,"Rajgir"
,"Yellandu"
,"Sathyamangalam"
,"Pilibanga"
,"Morshi"
,"Pehowa"
,"Sonepur"
,"Pappinisseri"
,"Zamania"
,"Mihijam"
,"Purna"
,"Puliyankudi"
,"Shikarpur, Bulandshahr"
,"Umaria"
,"Porsa"
,"Naugawan Sadat"
,"Fatehpur Sikri"
,"Manuguru"
,"Udaipur"
,"Pipar City"
,"Pattamundai"
,"Nanjikottai"
,"Taranagar"
,"Yerraguntla"
,"Satana"
,"Sherghati"
,"Sankeshwara"
,"Madikeri"
,"Thuraiyur"
,"Sanand"
,"Rajula"
,"Kyathampalle"
,"Shahabad, Rampur"
,"Tilda Newra"
,"Narsinghgarh"
,"Chittur-Thathamangalam"
,"Malaj Khand"
,"Sarangpur"
,"Robertsganj"
,"Sirkali"
,"Radhanpur"
,"Tiruchendur"
,"Utraula"
,"Patratu"
,"Vijainagar, Ajmer"
,"Periyasemur"
,"Pathri"
,"Sadabad"
,"Talikota"
,"Sinnar"
,"Mungeli"
,"Sedam"
,"Shikaripur"
,"Sumerpur"
,"Sattur"
,"Sugauli"
,"Lumding"
,"Vandavasi"
,"Titlagarh"
,"Uchgaon"
,"Mokokchung"
,"Paschim Punropara"
,"Sagwara"
,"Ramganj Mandi"
,"Tarakeswar"
,"Mahalingapura"
,"Dharmanagar"
,"Mahemdabad"
,"Manendragarh"
,"Uran"
,"Tharamangalam"
,"Tirukkoyilur"
,"Pen"
,"Makhdumpur"
,"Maner"
,"Oddanchatram"
,"Palladam"
,"Mundi"
,"Nabarangapur"
,"Mudalagi"
,"Samalkha"
,"Nepanagar"
,"Karjat"
,"Ranavav"
,"Pedana"
,"Pinjore"
,"Lakheri"
,"Pasan"
,"Puttur"
,"Vadakkuvalliyur"
,"Tirukalukundram"
,"Mahidpur"
,"Mussoorie"
,"Muvattupuzha"
,"Rasra"
,"Udaipurwati"
,"Manwath"
,"Adoor"
,"Uthamapalayam"
,"Partur"
,"Nahan"
,"Ladwa"
,"Mankachar"
,"Nongstoin"
,"Losal"
,"Sri Madhopur"
,"Ramngarh"
,"Mavelikkara"
,"Rawatsar"
,"Rajakhera"
,"Lar"
,"Lal Gopalganj Nindaura"
,"Muddebihal"
,"Sirsaganj"
,"Shahpura"
,"Surandai"
,"Sangole"
,"Pavagada"
,"Tharad"
,"Mansa"
,"Umbergaon"
,"Mavoor"
,"Nalbari"
,"Talaja"
,"Malur"
,"Mangrulpir"
,"Soro"
,"Shahpura"
,"Vadnagar"
,"Raisinghnagar"
,"Sindhagi"
,"Sanduru"
,"Sohna"
,"Manavadar"
,"Pihani"
,"Safidon"
,"Risod"
,"Rosera"
,"Sankari"
,"Malpura"
,"Sonamukhi"
,"Shamsabad, Agra"
,"Nokha"
,"PandUrban Agglomeration"
,"Mainaguri"
,"Afzalpur"
,"Shirur"
,"Salaya"
,"Shenkottai"
,"Pratapgarh"
,"Vadipatti"
,"Nagarkurnool"
,"Savner"
,"Sasvad"
,"Rudrapur"
,"Soron"
,"Sholingur"
,"Pandharkaoda"
,"Perumbavoor"
,"Maddur"
,"Nadbai"
,"Talode"
,"Shrigonda"
,"Madhugiri"
,"Tekkalakote"
,"Seoni-Malwa"
,"Shirdi"
,"SUrban Agglomerationr"
,"Terdal"
,"Raver"
,"Tirupathur"
,"Taraori"
,"Mukhed"
,"Manachanallur"
,"Rehli"
,"Sanchore"
,"Rajura"
,"Piro"
,"Mudabidri"
,"Vadgaon Kasba"
,"Nagar"
,"Vijapur"
,"Viswanatham"
,"Polur"
,"Panagudi"
,"Manawar"
,"Tehri"
,"Samdhan"
,"Pardi"
,"Rahatgarh"
,"Panagar"
,"Uthiramerur"
,"Tirora"
,"Rangia"
,"Sahjanwa"
,"Wara Seoni"
,"Magadi"
,"Rajgarh (Alwar)"
,"Rafiganj"
,"Tarana"
,"Rampur Maniharan"
,"Sheoganj"
,"Raikot"
,"Pauri"
,"Sumerpur"
,"Navalgund"
,"Shahganj"
,"Marhaura"
,"Tulsipur"
,"Sadri"
,"Thiruthuraipoondi"
,"Shiggaon"
,"Pallapatti"
,"Mahendragarh"
,"Sausar"
,"Ponneri"
,"Mahad"
,"Lohardaga"
,"Tirwaganj"
,"Margherita"
,"Sundarnagar"
,"Rajgarh"
,"Mangaldoi"
,"Renigunta"
,"Longowal"
,"Ratia"
,"Lalgudi"
,"Shrirangapattana"
,"Niwari"
,"Natham"
,"Unnamalaikadai"
,"PurqUrban Agglomerationzi"
,"Shamsabad, Farrukhabad"
,"Mirganj"
,"Todaraisingh"
,"Warhapur"
,"Rajam"
,"Urmar Tanda"
,"Lonar"
,"Powayan"
,"P.N.Patti"
,"Palampur"
,"Srisailam Project (Right Flank Colony) Township"
,"Sindagi"
,"Sandi"
,"Vaikom"
,"Malda"
,"Tharangambadi"
,"Sakaleshapura"
,"Lalganj"
,"Malkangiri"
,"Rapar"
,"Mauganj"
,"Todabhim"
,"Srinivaspur"
,"Murliganj"
,"Reengus"
,"Sawantwadi"
,"Tittakudi"
,"Lilong"
,"Rajaldesar"
,"Pathardi"
,"Achhnera"
,"Pacode"
,"Naraura"
,"Nakur"
,"Palai"
,"Morinda, India"
,"Manasa"
,"Nainpur"
,"Sahaspur"
,"Pauni"
,"Prithvipur"
,"Ramtek"
,"Silapathar"
,"Songadh"
,"Safipur"
,"Sohagpur"
,"Mul"
,"Sadulshahar"
,"Phillaur"
,"Sambhar"
,"Prantij"
,"Nagla"
,"Pattran"
,"Mount Abu"
,"Reoti"
,"Tenu dam-cum-Kathhara"
,"Panchla"
,"Sitarganj"
,"Pasighat"
,"Motipur"
,"O' Valley"
,"Raghunathpur"
,"Suriyampalayam"
,"Qadian"
,"Rairangpur"
,"Silvassa"
,"Nowrozabad (Khodargama)"
,"Mangrol"
,"Soyagaon"
,"Sujanpur"
,"Manihari"
,"Sikanderpur"
,"Mangalvedhe"
,"Phulera"
,"Ron"
,"Sholavandan"
,"Saidpur"
,"Shamgarh"
,"Thammampatti"
,"Maharajpur"
,"Multai"
,"Mukerian"
,"Sirsi"
,"Purwa"
,"Sheohar"
,"Namagiripettai"
,"Parasi"
,"Lathi"
,"Lalganj"
,"Narkhed"
,"Mathabhanga"
,"Shendurjana"
,"Peravurani"
,"Mariani"
,"Phulpur"
,"Rania"
,"Pali"
,"Pachore"
,"Parangipettai"
,"Pudupattinam"
,"Panniyannur"
,"Maharajganj"
,"Rau"
,"Monoharpur"
,"Mandawa"
,"Marigaon"
,"Pallikonda"
,"Pindwara"
,"Shishgarh"
,"Patur"
,"Mayang Imphal"
,"Mhowgaon"
,"Guruvayoor"
,"Mhaswad"
,"Sahawar"
,"Sivagiri"
,"Mundargi"
,"Punjaipugalur"
,"Kailasahar"
,"Samthar"
,"Sakti"
,"Sadalagi"
,"Silao"
,"Mandalgarh"
,"Loha"
,"Pukhrayan"
,"Padmanabhapuram"
,"Belonia"
,"Saiha"
,"Srirampore"
,"Talwara"
,"Puthuppally"
,"Khowai"
,"Vijaypur"
,"Takhatgarh"
,"Thirupuvanam"
,"Adra"
,"Piriyapatna"
,"Obra"
,"Adalaj"
,"Nandgaon"
,"Barh"
,"Chhapra"
,"Panamattom"
,"Niwai"
,"Bageshwar"
,"Tarbha"
,"Adyar"
,"Narsinghgarh"
,"Warud"
,"Asarganj"
,"Sarsod",];
$( "#automplete-2" ).autocomplete({
               source: availableTutorials,
               autoFocus:true
            });
         });
      </script>
</head>
<body>
    <nav class="navbar sticky-top navbar-expand-lg navbar-light bg-light">
          <a class="navbar-brand" href="#">
    <img src="images/logo.png" style="background-color: black;margin: 0px;padding: 0px;"width="60" height="60" alt="" >
          </a>
          <div class="navbar-collapse collapse w-100 order-3 dual-collapse2">
        <ul class="navbar-nav ml-auto">
            <li class="nav-item">
                <a class="nav-link " href="landingpage.php">Home</a>
            </li>
             <li class="nav-item">
                <a class="nav-link" href="flights.php">Flights</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="packages/packages.php">Package</a>
            </li>

             <li class="nav-item">
                <a class="nav-link" href="packages/PlacesToBe.php">Vacations</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="contactus.php">Contact Us</a>
            </li>
        </ul>
    </div>
    </nav>

  <div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
          <div class="carousel-inner">
            <div class="carousel-item active">
              <img src="images/15.jpg" class="d-block w-100" alt="...">
            </div>
            <div class="carousel-item">
              <img src="images/16.jpg" class="d-block w-100" alt="...">
            </div>
            <div class="carousel-item">
              <img src="images/18.jpg" class="d-block w-100" alt="...">
            </div>
          </div>
          <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
          </a>
          <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
          </a>
          </div>
         <form action="landingpage.php?t=true" method="POST" >
          <div class="row">
          <div class="centered col-md-10 col-md-offset-1 "><h1 for ="automplete-2" style="text-align: center;">Where Do You Want To Go?</h1></div>
          
 
          <div > 

            <input class="forminput inp"id = "automplete-2" type="text" name="searchValue" >
                <input class="searchbutton" type="submit" name="Search" value="Search">
         
           	 </div>
          	</div>
          	</form>

        <!--   <form>
          <div class="row">
          <div class="centered col-md-10 col-md-offset-1 "><h1 for ="automplete-2" style="text-align: center;">Where Do You Want To Go?</h1></div>
          <div > <input class="forminput inp"id = "automplete-2" type="text" autocomplete="off" name="searchValue" >
                  <input class="searchbutton" type="submit" name="Search" value="Search">
            </div>
          </div>
        </form> -->

<div class="section-grey">
    <div class="container text-center">

      <div class="three-brand-icons">
        
        <div class="row">
            
            <div class="col-md-4 brand-icon"> <a href="#"> 
              <img src="images/icon1.png" height="70px" class="center-block">
                  </a>
              <h4>Adventures</h4>
              <p>Privately guided treks and adventures combining superb local guides with world class standards. </p>
            </div>
      

            
            <div class="col-md-4 brand-icon">
               <a href="#"> 
              <img src="images/icon2.png" height="70px" class="center-block">
               </a>
              <h4>Adventures</h4>
              <p>Privately guided treks and adventures combining superb local guides with world class standards. </p>
            </div>
         

         
            <div class="col-md-4 brand-icon">
               <a href="#">
              <img src="images/icon3.png" height="70px" class="center-block">
               </a>  
              <h4>Family Adventures</h4>
              <p>The ultimate bucket list for adventurous families, holidays designed for families by families.</p>
            </div>
         
        </div>

      </div>
    </div>
  </div>




<div class="map">
<div class="container add-info" >

    <div class="row"> 
      <div class="col-md-4 col-md-offset-4">
    <h1 class="containerHeading"  > <span>Best</span> Places To Be</h1>
    </div>
  </div> 
  <div class="row" >
          <div class="col-sm">
            <a href=""><img  class="colImg" src="images/kerala.jpg"></a>
            <p class="colp" <a href=""><strong>Kerala</strong> is one of the prettiest states, rightfully dubbed ‘God’s Own Country’. Here you will find pristine beaches at Kovalam, Muzhappilangad and Varkala. Besides beaches, the state also has a plethora of historical monuments, enthralling waterfalls and some breathtaking hill stations.  </p>
             <button type="button" class="btn btn-primary btn-sm">Learn More</button>
          </div>
          <div class="col-sm">
            <a href=""><img  class="colImg " src="images/Karnataka.jpg"></a>
                  <p class="colp" ><strong> Karnataka </strong> state is also called the ‘land of temples’ because of the multitude of these religious structures here. Right from hill stations to ancient temples, there is something for everyone in Karnataka. There are popular protected monuments  of Hampi.</p>
             <button type="button" class="btn btn-primary btn-sm">Learn More</button>
          </div>
          <div class="col-sm">
              <a href=""><img class="colImg" src="images/punjab.jpg"></a>
                    <p class="colp"><strong>Punjab </strong> is known for its rich and religious history, its cultural diversity and the lip-smacking Punjabi cuisine. It is also home to the iconic Golden Temple that draws devotees from all around the world. Here you will find a blend of local culture and ancient history. </p>
             <button type="button" class="btn btn-primary btn-sm">Learn More</button>
          </div>

   

          <div class="col-sm">
            <a href=""><img  class="colImg" src="images/Rajasthan.jpg"></a>
            <p class="colp" <a href=""><strong>Rajasthan</strong>  will tell you stories about wars, victories, romances and men of valor. Rajasthan is the land of kings and has a rich history. You can see palaces, archaic monuments and staggering forts. </p>
             <button type="button" class="btn btn-primary btn-sm">Learn More</button>
          </div>
          <div class="col-sm">
            <a href=""><img  class="colImg " src="images/Gujarat.jpg"></a>
                  <p class="colp" ><strong> Gujarat</strong>  every year sees an inflow of tourists who visit the beaches, temples and archaeological survey sites. Gujarat also is the home to the largest protected area dedicated to Asiatic lions. The state is the birthplace of Mahatma Gandhi. </p>
             <button type="button" class="btn btn-primary btn-sm">Learn More</button>
          </div>
          <div class="col-sm">
              <a href=""><img class="colImg" src="images/Himachal-Pradesh.jpg"></a>
                    <p class="colp"><strong>Himachal Pradesh </strong> lies in the foothills of the Himalayan mountain range, and you can see the snow-capped mountains amidst the lush greenery. There are a number of great hill stations to visit.  </p>
             <button type="button" class="btn btn-primary btn-sm">Learn More</button>
         
          </div>
  </div>

</div>
</div>
<div class=" tttravel ">


</div>
</div>



<div class="container">
  <div class="row hotels">
    
          <div class="col-md-8"> <div class="hotels1"></div><h4> Oberoi Hotels</h4> <p> Oberoi Hotels & Resorts presents award winning luxury hotels and resorts in India, Indonesia, Mauritius, Egypt and Saudi Arabia & The UAE</p> <button type="button" class="btn btn-primary btn-sm">Learn More</button></div>

          <div class="col-md-4"> <div class="hotels2"></div><h4> Taj Hotel</h4> <p> Book Best Luxury Hotels & Resorts in the World </p><button type="button" class="btn btn-primary btn-sm">Learn More</button></div>

          <div class="col-md-4"> <div class="hotels3"></div><h4> GeeKay Millenniaa </h4> <p> Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore</p><button type="button" class="btn btn-primary btn-sm">Learn More</button></div>

           <div class="col-md-4"> <div class="hotels4"></div><h4> V Residency</h4> <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore</p><button type="button" class="btn btn-primary btn-sm">Learn More</button></div>

           <div class="col-md-4"> <div class="hotels5"></div><h4> Helios</h4> <p> Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore</p><button type="button" class="btn btn-primary btn-sm">Learn More</button></div>

  </div>
</div>

 <!--End of MainBody-->

    <!--Footer-->

    <footer class="py-4" style="margin-top: 272px;">
        <div class="text-center text-white container">
            <p class="my-4 h6">Stay updated with our latest trends</p>
            <form class="form-inline d-flex form-group container justify-content-center">
                <input class="form-control mr-sm-1 mb-2" type="search" placeholder="Enter email">
                <button class="btn btn-primary mb-2" type="submit"><i class="fa fa-arrow-right"></i></button>
            </form>
            <p>
                <a class="text-white" href="#"><i class="fa fa-whatsapp"></i></a>&nbsp;
                <a class="text-white" href="#"><i class="fa fa-pinterest-p"></i></a>&nbsp;
                <a class="text-white" href="#"><i class="fa fa-google-plus"></i></a>&nbsp;
                <a class="text-white" href="#"><i class="fa fa-twitter"></i></a>&nbsp;
                <a class="text-white" href="#"><i class="fa fa-dribbble"></i></a>
            </p>
            <span class="foot-text">Copyright 2019 Travel | All rights reserved.</span>
        </div>
    </footer>

    <!--End of Footer-->


</body>
</html>